name: Publish package to PyPi

on:
  push:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip==25.1.1;
          python -m pip install --default-timeout=100 $(cat requirements-dev.txt | grep hatch)

      - name: Build distribution
        run: hatch build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.12.4

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
