name: Package - test

on:
  push:
    paths:
      - "mof_circular_105_2020/**"
      - "tests/**"
      - ".github/workflows/test.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu:22.04
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python on version ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |

          # Install
          python -m pip install --upgrade pip==25.1.1;
          python -m pip install --default-timeout=100 $(cat requirements-dev.txt | grep hatch)

      - name: Test package
        run: |

          # Run
          hatch run test tests;
