name: Application - Unit-test

on:
  push:
    paths:
      - "mof_circular_105_2020/**"
      - "tests/unit/**"
  workflow_dispatch:

jobs:
  unit-test:
    # Configuration
    runs-on: ubuntu-latest

    # Related to Python not usable in ubuntu:20.04. Upgrade to 22.04.
    # Ref https://github.com/actions/setup-python/issues/560
    container: ubuntu:22.04
    strategy:
      matrix:
        python-version: [
            "3.9",
            "3.10",
            "3.11",
            "3.12",
          ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python on version ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          # ref: This has been error by cache - so don't push it
          # removed related fixed to: https://github.com/bend-n/godot-actions/commit/c5e255a39b21b74a33a47151ae68f2b0f7e391d0
          # cache: 'pip'
          # cache-dependency-path: '**/requirements-dev.txt'

      - name: Install dependencies
        run: |

          # Install element
          python -m pip install --upgrade pip==24.1.1;
          python -m pip install --default-timeout=100 $(cat requirements-dev.txt | grep hatch)

      - name: Package - Test unit-test progress
        run: |

          # Run test on unit test only
          hatch run test tests/unit;
